language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install pep8
  - pip install codecov
script:
  - pep8 .
  - coverage run --source=wtouch setup.py test
after_success:
  - codecov